Document: libfb303
Title: Debian libfb303 Manual
Author: <insert document author here>
Abstract: This manual describes what libfb303 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libfb303/libfb303.sgml.gz

Format: postscript
Files: /usr/share/doc/libfb303/libfb303.ps.gz

Format: text
Files: /usr/share/doc/libfb303/libfb303.text.gz

Format: HTML
Index: /usr/share/doc/libfb303/html/index.html
Files: /usr/share/doc/libfb303/html/*.html
